name: 'aws_price_list'
version: '1.0.0'
config-version: 2

profile: 'snowflake-trial'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  aws_price_list:
    +materialized: table
    +transient:    false

vars:
  database: 'demo_db'
  schema:   'aws_price_list'